# Generated by Django 4.0.5 on 2022-06-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='username',
            new_name='user',
        ),
    ]
