# Generated by Django 4.0.5 on 2022-06-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_testimonials_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='post_date',
            new_name='post_date_time',
        ),
    ]
