# Generated by Django 4.0.5 on 2022-06-14 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_qnaforum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QnAForum',
            new_name='QuestionAnswerForum',
        ),
    ]
