# Generated by Django 4.0.5 on 2022-06-15 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_qnaforum_questionanswerforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerforum',
            name='post_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
