# Generated by Django 4.0.5 on 2022-06-16 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventideas_eventimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventideas',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='event_idea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='events.eventideas'),
        ),
    ]
