# Generated by Django 4.0.5 on 2022-06-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventideas_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimages',
            name='event_image_details',
        ),
        migrations.RemoveField(
            model_name='eventimages',
            name='event_image_title',
        ),
    ]
