# Generated by Django 4.0.5 on 2022-06-17 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_remove_eventimages_event_image_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimages',
            name='event_image_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventimages',
            name='event_image_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='EventReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_review', models.TextField()),
                ('event_idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='events.eventideas')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
