# Generated by Django 4.0.5 on 2022-06-21 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventcategories_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreviews',
            name='post_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswerforum',
            name='post_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
