# Generated by Django 4.0.5 on 2022-06-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventreviews_post_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventideas',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventimages',
            old_name='event_idea_id',
            new_name='event_idea',
        ),
        migrations.RenameField(
            model_name='eventreviews',
            old_name='event_idea_id',
            new_name='event_idea',
        ),
    ]
