# Generated by Django 4.0.5 on 2022-06-09 06:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Username')),
                ('f_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('contact_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('is_event_manager', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
