# Generated by Django 4.0.5 on 2022-06-10 06:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=200, validators=[accounts.models.validate_name], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=200, validators=[accounts.models.validate_name], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[accounts.models.validate_username], verbose_name='Username'),
        ),
    ]
