# Generated by Django 4.0.5 on 2022-06-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_f_name_alter_user_l_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_num',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
