# Generated by Django 4.0.5 on 2022-06-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendordetails_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcategories',
            name='vendor_category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
