# Generated by Django 4.0.5 on 2022-06-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_vendordetails_vendorregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_image', models.ImageField(upload_to='vendor_images/')),
                ('vendor_image_title', models.CharField(max_length=200)),
                ('vendor_image_details', models.TextField()),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorregistration')),
            ],
        ),
    ]
