# Generated by Django 4.0.5 on 2022-06-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorimages',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='vendors.vendorregistration'),
        ),
    ]
