# Generated by Django 4.0.5 on 2022-06-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendorimages_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorimages',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
